/**
 * What the UI audit visits (scripts/audit.mjs).
 *
 * seeds           URLs to start from; the full audit also follows the links it finds on them.
 *                 A route with an [id] needs at least one seed, or the quick audit cannot open it.
 * main            the three pages of the app the quick audit always checks
 * langPages       where the header's language switcher is exercised
 * guest*          patient app only: what is public, what must ask for a login
 */
export const APPS = {
  patient: {
    home: "/patient",
    main: ["/patient", "/patient/appointments", "/patient/records"],
    demo: "demoPatient",
    seeds: [
      "/",
      "/login",
      "/register",
      "/register?role=doctor",
      "/forgot-password",
      "/no-such-page",
      "/patient",
      "/patient/doctors",
      "/patient/doctors/doc-1",
      "/patient/doctors/doc-1/book",
      "/patient/doctors/doc-1/book?reschedule=apt-1",
      "/patient/appointments",
      "/patient/appointments/apt-1",
      "/patient/appointments/apt-4",
      "/patient/appointments/apt-6",
      "/patient/records",
      "/patient/records/print",
      // ?state= previews are no longer linked from the UI (the toggle row is gone), so they are seeded here
      "/patient/doctors?state=empty",
      "/patient/doctors?state=loading",
      "/patient/doctors?state=error",
      "/patient/appointments?state=empty",
      "/patient/appointments?state=loading",
      "/patient/appointments?state=error",
      "/patient/records?state=empty",
      "/patient/records?state=loading",
      "/patient/records?state=error",
      "/patient/chat?state=empty",
      "/patient/chat?state=loading",
      "/patient/chat?state=error",
      "/patient/records/print?mode=doctor&period=1y&sections=analysis,summary",
      "/patient/records/print?record=rec-1",
      "/patient/chat",
      "/patient/chat/chat-1",
      "/patient/profile",
      "/patient/review/apt-4",
      "/patient/review/apt-5",
      "/patient/chat/new?with=doc-2",
      // "ask the doctor": the chat opens with a notebook entry attached (approved entries only)
      "/patient/chat/chat-1?record=rec-13",
      "/patient/chat/new?with=doc-2&record=rec-4",
      "/patient/records/print?record=rec-15",
      "/patient/doctors/doc-1?from=doctor",
      "/patient/doctors/doc-1?from=admin",
      // notebook search and period (the filters live in the URL), and a print of a hand-picked range
      "/patient/records?q=gemoglobin",
      "/patient/records?q=zzzz",
      "/patient/records?from=2026-01-01&to=2026-06-30",
      "/patient/records/print?from=2026-01-01&to=2026-06-30",
      // a doctor without a price: the booking has no payment block
      "/patient/doctors/doc-4/book",
      // an appointment id the server has never seen (booked in another browser)
      "/patient/appointments/apt-local-1",
    ],
    langPages: ["/login", "/patient/appointments/apt-1", "/patient/doctors?state=empty"],
    profileLang: "/patient/profile",
    // Browsable without a session; everything else under /patient must redirect to /login?returnTo=…
    guestPages: ["/", "/patient/doctors", "/patient/doctors/doc-1"],
    guestProtected: ["/patient", "/patient/appointments", "/patient/chat/chat-1", "/patient/doctors/doc-1/book"],
    guestDoctor: "/patient/doctors/doc-1",
  },
  doctor: {
    home: "/doctor",
    main: ["/doctor", "/doctor/appointments", "/doctor/patients/u-patient-1"],
    demo: "demoDoctor",
    seeds: [
      "/",
      "/login",
      "/no-such-page",
      "/doctor",
      "/doctor?state=pending",
      "/doctor/onboarding",
      "/doctor/appointments",
      "/doctor/appointments/apt-1",
      "/doctor/appointments/apt-8",
      "/doctor/appointments/apt-9",
      "/doctor/schedule",
      "/doctor/patients",
      "/doctor/patients/u-patient-1",
      "/doctor/patients/u-patient-1/print",
      "/doctor/appointments?state=empty",
      "/doctor/appointments?state=loading",
      "/doctor/appointments?state=error",
      "/doctor/patients?state=empty",
      "/doctor/patients?state=loading",
      "/doctor/patients?state=error",
      "/doctor/chat?state=empty",
      "/doctor/chat?state=loading",
      "/doctor/chat?state=error",
      "/doctor/chat",
      "/doctor/chat/dchat-1",
      "/doctor/reviews",
      "/doctor/profile",
      "/doctor/chat/new?with=u-patient-5",
      "/doctor/chat/dchat-2",
      "/doctor/chat/new?with=u-patient-2&record=rec-21",
      // calendar views (list is the default)
      "/doctor/appointments?view=week",
      "/doctor/appointments?view=month",
      "/doctor/appointments?view=week&date=2026-10-15",
      "/doctor/appointments?view=month&state=empty",
      "/doctor/patients/u-patient-1?q=ekg",
    ],
    langPages: ["/login", "/doctor/patients/u-patient-1"],
    profileLang: "/doctor/profile",
  },
  admin: {
    home: "/admin",
    main: ["/admin", "/admin/applications", "/admin/records"],
    demo: "demoAdmin",
    seeds: [
      "/",
      "/login",
      "/no-such-page",
      "/admin",
      "/admin/applications",
      "/admin/applications/doc-15",
      "/admin/applications/doc-18",
      "/admin/doctors",
      "/admin/doctors/doc-1",
      "/admin/reviews",
      "/admin/users",
      "/admin/profile",
      "/admin/records",
      "/admin/records/rec-16",
      "/admin/records/rec-17",
      "/admin/records/rec-private-1",
      // deleted by its author: still reviewable, with its history
      "/admin/records/rec-30",
      "/admin/records?state=empty",
      "/admin/records?state=loading",
      "/admin/records?state=error",
    ],
    langPages: ["/login", "/admin/applications/doc-15"],
    profileLang: "/admin/profile",
  },
};
